version: '2'

services:

  apollo-test-db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_TCP_PORT: "3336"
    ports:
      - "3311:3336"
networks:
  default:
    external:
      name: apollo-api_test
